### ISSUE TITLE
JSON deserialization of on-chain-metadata fails for array types

### ISSUE THREAD

**Issue by sourcelib-stack** [blockfrost/blockfrost-java#3]
Hi,

For some assets there are properties represented as arrays, example "images". 
For those the **assetService.getAsset(assetName);** fails with this error:
`Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)`

Example call: assetService.getAsset("4c9f7d6c24ba8e2b12f3269ac38d706025e39a50a524afe6eaf79d955665676769656d6174653036323031");

**Comment by bentaye** [comment]
I had a look and grabbed the Json for that asset on the mainnet

Here it is:
```
{
    "asset": "4c9f7d6c24ba8e2b12f3269ac38d706025e39a50a524afe6eaf79d955665676769656d6174653036323031",
    "policy_id": "4c9f7d6c24ba8e2b12f3269ac38d706025e39a50a524afe6eaf79d95",
    "asset_name": "5665676769656d6174653036323031",
    "fingerprint": "asset1fkk7ch07h25jpzdwh3l9zp8ds7fz525qjakwe5",
    "quantity": "1",
    "initial_mint_tx_hash": "c8c8c8f7dba6f8bdf0a5727f63106037f65cdd00d36558469a87729a4c97ced6",
    "mint_or_burn_count": 1,
    "onchain_metadata": {
        "name": "Veggiemate06201",
        "image": "ipfs://QmXr96HxoMXPKJTca8aAhJjhpuhQDus3SboXYgkDPT6XAE",
        "body": "Hoodie",
        "eyes": "Squint",
        "head": "Sticker",
        "files": [
            {
                "src": "ipfs://QmXr96HxoMXPKJTca8aAhJjhpuhQDus3SboXYgkDPT6XAE",
                    "name": "Veggiemate06201",
                    "mediaType": "image/png"
            }
        ],
        "mouth": "Skull",
        "mediaType": "image/png",
        "typeClass": "Red Onion",
        "background": "Pink",
        "description": ""
    },
    "metadata": null
}
```


The error comes from the `Asset` class where `onchainMetadata` is defined as a `Map<String, String>`

```
    /**
     * On-chain metadata stored in the minting transaction under label 721,
     * community discussion around the standard ongoing at
     * https://github.com/cardano-foundation/CIPs/pull/85
     */
    private Map<String, String> onchainMetadata;
```

The value for the "files" field does not fit in there. 
It should probably be a `Map<String, Object>`

**Comment by sourcelib-stack** [comment]
Indeed Map<String, Object> worked just fine for me.

**Comment by satran004** [comment]
@sourcelib-stack Possible to create a PR for this issue ? 

Otherwise, I will try to fix this.

**Comment by bentaye** [comment]
@satran004 @sourcelib-stack I can have a try, I found some assets on the testnet that I can use to make an IT for it along with the fix

**Comment by satran004** [comment]
@bentaye Did you try to fork the repo and create the PR ? By default, PR permission should be there for a fork.

**Comment by bentaye** [comment]
@satran004 oh I see! PR is open now

**Comment by mmahut** [comment]
Can this be closed?

**Comment by bentaye** [comment]
Double check with @satran004 but AFAIAC I would say yes. And this one too https://github.com/blockfrost/blockfrost-java/issues/2 as it seems to me that it is the same problem

**Comment by satran004** [comment]
This is already part of 0.1.1.
